name: Deploy
on:
  workflow_dispatch:
    inputs:
      project:
        description: "name of product to deploy"
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Building ${{github.event.inputs.project}}
        run: echo 'Build'
      - name: Deploying ${{github.event.inputs.project}}
        run: echo 'Deploy'
