name: setup-node
run-name: ${{github.workflow}} by ${{github.actor}}
on:
  push:
    branches-ignore:
      - "main"
jobs:
  check-bats-version:
    if: ${{false}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install -g bats
      - run: bats -v
